### ISSUE TITLE
Cleanup jupyter notebook

### ISSUE THREAD

**Issue by gabrieltorresgamez** [Smart-Classroom-Challenge/Data-Evaluation#4]
Beim mergen deines (@etiiiR) requests (#3) habe ich bemerkt, dass das Dokument jetzt sehr unstrukturiert / nicht einheitlich ist.

Kannst du bitte das Notebook bereinigen?
(Imports alle am gleichen Ort, Funktionen im Setup anstatt in der Auswertung, Bilder beschreiben oder rausnehmen, bei allen Plots die Grössen einheitlicher machen, weitere anomalien, etc)

Bitte Änderungen direkt ins main commiten. Ich werde bis Abschluss vom Ticket keine Änderungen daran machen, um keine conflicts zu verursachen. Danke :)

**Comment by etiiiR** [comment]
solved

**Comment by gabrieltorresgamez** [comment]
not yet solved, but ill do the rest

**Comment by gabrieltorresgamez** [comment]
solved with commit 9c5ff5c
